# Generated by Django 2.2 on 2020-04-28 08:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ico_monitoring', '0004_add_replicant_collaboration'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concept', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=25)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('user', models.CharField(max_length=50)),
                ('errors', models.TextField(null=True)),
                ('num_rows', models.IntegerField(null=True)),
                ('input_file', models.CharField(max_length=100)),
                ('monitoringscheme', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ico_monitoring.MonitoringScheme')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
