# Generated by Django 2.2.13 on 2020-11-12 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djimporter', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='importlog',
            name='percent',
            field=models.SmallIntegerField(default=0),
        ),
    ]
