# Generated by Django 2.2.13 on 2020-11-13 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djimporter', '0003_auto_20201113_1148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importlog',
            name='input_file',
            field=models.CharField(max_length=255),
        ),
    ]
